version: "3.8"

services:
  mongo:
    container_name: mongo-warrion
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - warrion_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  back:
    container_name: back-warrion
    build:
      context: ../Back_Warrion/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/warrion
      # - FRONTEND_URL=http://localhost:8088
      - FRONTEND_URL=http://51.77.137.168:8088
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - warrion_network
      # - nginx-proxy-manager_default
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:3000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  front:
    container_name: front-warrion
    build:
      context: .
      dockerfile: dockerfile
      args:
        # - VITE_API_URL=http://localhost:3000
        - VITE_API_LOCAL_URL=http://51.77.137.168:3000
    ports:
      - "8088:80"
    restart: always
    depends_on:
      back:
        condition: service_healthy
    networks:
      - warrion_network
      # - nginx-proxy-manager_default
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:80/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

volumes:
  mongo_data:

networks:
  warrion_network:
  # nginx-proxy-manager_default:
  #   external: true
